# Generated by Django 4.2.14 on 2026-06-03 05:29
# Modified: Changed to noop to prevent accidental deletion of user cart data.
# The Cart/CartItem tables are preserved and any schema adjustments
# are handled by migration 0010 in an idempotent, non-destructive way.

from django.db import migrations


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_coupon_order_discount'),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
