# Generated by Django 4.2.14 on 2026-06-03 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_coupon_order_discount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
