# Generated by Django 4.2.14 on 2026-06-03 05:35
# Modified: Changed to noop to avoid "table already exists" errors when
# tables were preserved by migration 0008. All actual table creation
# and schema adjustments are handled by migration 0010 in an idempotent way.

from django.db import migrations


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_cartitem_unique_together_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
